### ISSUE TITLE
Found Ransomware

### ISSUE THREAD

**Issue by LukeMedeiros916** [NoelisTired/TikTok-Sharebot#2]
![Screenshot 2022-04-17 225658](https://user-images.githubusercontent.com/71280264/163762260-49c1185a-32fc-41e1-8088-0076fbf1cf56.png)

Well, I guess you can only cover up NOELP X AIO so much. I dug into your program and found these ransom encryptors

**Comment by LukeMedeiros916** [comment]
> ![Screenshot 2022-04-17 225658](https://user-images.githubusercontent.com/71280264/163762260-49c1185a-32fc-41e1-8088-0076fbf1cf56.png)
> 
> Well, I guess you can only cover up NOELP X AIO so much. I dug into your program and found these ransom encryptors

Might want me on your team to clean your program up.... Luke Medeiros#6969

**Comment by TheBlackCookie** [comment]
how is that ransomeware? you might wanna go and check what ransomeware is again... deadass 🤡

**Comment by NoelisTired** [comment]
I'm afraid you have no idea what ransomware is, we're not keeping your data. and we're most definitely never keeping it for ransom.
Luke, it seems to me that you've just found out PyArmor exists! ( https://github.com/dashingsoft/pyarmor )
Must've been a miracle seeing that (almost) every tool with PyArmor has 4/69 detections!
As you might've known we use Selenium, therefore downloading ChromeDriver off https://chromedriver.chromium.org/downloads
This is stored in %temp%. That explains the write permissions you were talking about!
We use PSUTIL for scanning for debuggers and other malicious software.
Honestly, I think you should check your facts. considering you've embarrassed yourself right here.
I've sent you a friend request on discord if you have additional questions
